__copyright__ = 'Copyright © by tracetronic GmbH, Dresden'
__license__ = (
    "This file is distributed as an integral part of tracetronic's software products "
    'and may only be used in connection with and pursuant to the terms and conditions '
    'of a valid tracetronic software product license.'
)


from enum import Enum

class BlockEvent(Enum):
    """Events that trigger state transitions."""
    FAILED_EXECUTION = ...
    FINISHED_EXECUTION = ...
    PARAMETER_CAN_NOT_BE_APPLIED = ...
    PRECONDITION_FULFILLED = ...
    PARAMETERS_RESOLVED = ...
    PRECONDITION_FAILED = ...
    FORCE_SKIP = ...